# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint for user packs

Globals:
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SavePacksQueue

Resources:
    SavePacksQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-packs-queue
            VisibilityTimeout: 601
    RetrievePacksFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-packs.default
            Runtime: nodejs18.x
            CodeUri: ./dist/retrieve-packs
            Timeout: 29
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-packs-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    StartSavePacksFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-packs.default
            Runtime: nodejs18.x
            CodeUri: ./dist/start-save-packs
            Timeout: 5
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-packs-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    ProcessSavePacksFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-packs.default
            Runtime: nodejs18.x
            CodeUri: ./dist/process-save-packs
            MemorySize: 128
            ReservedConcurrentExecutions: 5
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-packs
            Timeout: 60
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SavePacksQueue.Arn
                        BatchSize: 60
                        MaximumBatchingWindowInSeconds: 60